### ISSUE TITLE
todo list air track doc

### ISSUE THREAD

**Issue by jcolomb** [open-make/airtrack-doc-website#1]
HARDWARE QUESTIONS
- [x] mpr placement + detectors placement + licking spots
- [x] pixy cam mount (extra 3d printing)
- [x] find a stable clamp for actuator
- [x] get info from workshop
     - balls and cylinder for balls
- [x] check English
- [x] better structure (group information in a way),  sub structure toc
- [x] review where we need (good) pictures
